version: '3.8'
services:
  
  database:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_USERNAME=pc_user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=prime-condies
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
